In [2]:
import numpy as np

In [3]:
def create_ij_array(m, n):
    """
    Creates a m x n numpy 2D array with element i, j = i * j.

    Args:
        m (int): Number of rows in the array.
        n (int): Number of columns in the array.

    Returns:
        numpy.ndarray: A m x n numpy 2D array with dtype numpy.float64
                       where element at position (i, j) is i * j.
    """
    row_indices = np.arange(m, dtype=np.float64).reshape(m, 1) # Create column vector of row indices (0 to m-1)
    col_indices = np.arange(n, dtype=np.float64).reshape(1, n) # Create row vector of column indices (0 to n-1)
    # Broadcasting: row_indices (m, 1) and col_indices (1, n) are broadcast to (m, n) for element-wise multiplication.
    result_array = row_indices * col_indices # Element-wise multiplication to get i*j at position (i, j)
    return result_array

# Example usage of create_ij_array
print("create_ij_array(3, 4):\n", create_ij_array(3, 4))

create_ij_array(3, 4):
 [[0. 0. 0. 0.]
 [0. 1. 2. 3.]
 [0. 2. 4. 6.]]


In [4]:
def normalize_array_columns(array_2d):
    """
    Computes column-normalized array (column sum = 1).

    Args:
        array_2d (numpy.ndarray): Input 2D numpy array.

    Returns:
        numpy.ndarray: A new 2D numpy array where each column sums to 1.
                       The original array is not modified.
    """
    column_sums = np.sum(array_2d, axis=0) # Calculate sum of each column (axis=0)
    # Broadcasting: column_sums (n,) broadcasts to (m, n) to divide each column of array_2d by its sum.
    normalized_array = array_2d / column_sums # Divide each column by its sum for normalization
    return normalized_array

# Example usage of normalize_array_columns
input_columns = np.array([
    [1.0, 2.0, 6.0, 4.0],
    [3.0, 4.0, 3.0, 7.0],
    [1.0, 4.0, 6.0, 9.0]
])
print("\nnormalize_array_columns(input_columns):\n", normalize_array_columns(input_columns))


normalize_array_columns(input_columns):
 [[0.2  0.2  0.4  0.2 ]
 [0.6  0.4  0.2  0.35]
 [0.2  0.4  0.4  0.45]]


In [5]:
def normalize_array_rows(array_2d):
    """
    Computes row-normalized array (row sum = 1).

    Args:
        array_2d (numpy.ndarray): Input 2D numpy array.

    Returns:
        numpy.ndarray: A new 2D numpy array where each row sums to 1.
                       The original array is not modified.
    """
    row_sums = np.sum(array_2d, axis=1) # Calculate sum of each row (axis=1)
    # Reshape row_sums (m,) to (m, 1) to enable row-wise division through broadcasting.
    normalized_array = array_2d / row_sums.reshape(-1, 1) # Divide each row by its sum for normalization
    # Broadcasting: row_sums.reshape(-1, 1) (m, 1) broadcasts to (m, n) for element-wise division.
    return normalized_array

# Example usage of normalize_array_rows
input_rows = np.array([
    [1.0, 3.0, 1.0],
    [2.0, 4.0, 4.0],
    [6.0, 3.0, 6.0],
    [4.0, 7.0, 9.0]
])
print("\nnormalize_array_rows(input_rows):\n", normalize_array_rows(input_rows))


normalize_array_rows(input_rows):
 [[0.2  0.6  0.2 ]
 [0.2  0.4  0.4 ]
 [0.4  0.2  0.4 ]
 [0.2  0.35 0.45]]


In [6]:
def negatives_to_zeros(array):
    """
    Returns array with negative elements set to 0 (original array unchanged) using masking.

    Args:
        array (numpy.ndarray): Input numpy array of any shape.

    Returns:
        numpy.ndarray: A new numpy array with the same shape as input,
                       but with all negative elements replaced by 0.
                       The original array is not modified.
    """
    tmp = array.copy() # Create a copy of the input array to avoid modifying the original
    tmp[array < 0] = 0    # Use the mask to set elements corresponding to True (negative elements) to 0 in the copy
    return tmp

# Example usage of negatives_to_zeros
test_negatives = np.array([
    [1, -2, 3],
    [-4, 5, -6]
])
print("\nnegatives_to_zeros(test_negatives):\n", negatives_to_zeros(test_negatives))
print("\nOriginal array (test_negatives - unchanged):\n", test_negatives)


negatives_to_zeros(test_negatives):
 [[1 0 3]
 [0 5 0]]

Original array (test_negatives - unchanged):
 [[ 1 -2  3]
 [-4  5 -6]]


In [7]:
def sum_of_product(a, b):
    """
    Computes the sum of elements of the product of two matrices.
    Assumes input matrices 'a' and 'b' are valid for matrix multiplication.

    Args:
        a (array-like): First matrix (numpy array or list of lists).
        b (array-like): Second matrix (numpy array or list of lists).

    Returns:
        numpy.number: The sum of all elements in the matrix product of a and b.
    """
    return (a @ b).sum() # Efficient matrix multiplication (@ operator) and sum of all elements

# Example usage of sum_of_product
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])
print("\nsum_of_product(matrix_a, matrix_b):\n", sum_of_product(matrix_a, matrix_b))


sum_of_product(matrix_a, matrix_b):
 134
